name: 🔗 Broken Link Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # daily at 2 AM UTC
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install lychee
        run: |
          curl -LsSf https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin

      - name: Run lychee broken link check
        run: |
          lychee --verbose --no-progress './docs/**/*.md' './public/**/*.html' './**/*.md' './**/*.html'
            lychee --output-format text --output-file lychee-report.txt
          cat lychee-report.txt

      - name: Fail if broken links found
        run: |
          if grep -q "✗" lychee-report.txt; then
            echo "Broken links found! ❌"
            exit 1
          else
            echo "No broken links found! ✅"
          fi
