name: 🔗 Broken Link Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  check-links:
    name: Check for broken links using latest Lychee
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 📥 Install Latest Lychee (link checker)
        run: |
          curl -LsSf https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz -o lychee.tar.gz
          tar -xzf lychee.tar.gz
          sudo mv lychee /usr/local/bin

      - name: 🔍 Run Lychee on all .md and .html files
        run: |
          lychee --verbose --no-progress --no-exclude --output lychee-report.txt './**/*.md' './**/*.html' || true
          cat lychee-report.txt

      - name: 🚨 Fail if broken links found
        run: |
          if grep -q "✗" lychee-report.txt; then
            echo "❌ Broken links detected."
            exit 1
          else
            echo "✅ No broken links found."
          fi
